# Generated by Django 3.2.9 on 2021-11-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211108_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='project_comment', to='api.ProjectComment'),
        ),
    ]
