# Generated by Django 3.2 on 2021-11-16 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projecttask_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='filter_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
